version: 1.0.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2017

# clone directory
clone_folder: c:\projects\Resource File Translator
  
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

environment:
  my_secret:
    secure: eXAIysIG8npt2tVMYQpGwTLj47CK9lUB/NyEfVGgc90=

install:
- nuget install secure-file -ExcludeVersion
- secure-file\tools\secure-file -decrypt "c:\projects\Resource File Translator\Resource File Translator\Resource File Translator.snk.enc" -secret %my_secret%

# NSIS Paths
# https://www.appveyor.com/docs/build-environment/#tools
- set PATH=%PATH%;C:\Program Files (x86)\NSIS;

# NSIS Plugin (NsisDotNetChecker)
- appveyor DownloadFile https://github.com/ReVolly/NsisDotNetChecker/archive/master.zip
- 7z e master.zip -o"C:\Program Files (x86)\NSIS\Include" DotNetChecker.nsh -r
- 7z e master.zip -o"C:\Program Files (x86)\NSIS\Plugins\x86-ansi" DotNetChecker.dll -r

after_build:
- cmd: 7z a Resource.File.Translator.Portable.zip "c:\projects\Resource File Translator\Resource File Translator\bin\Release\"
- cmd: makensis.exe "c:\projects\Resource File Translator\Resource File Translator\Setup\Resource File Translator.nsi"

artifacts:
- path: Resource.File.Translator.Setup.exe
- path: Resource.File.Translator.Portable.zip

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: '// TODO: Write Release Notes'
  provider: GitHub
  auth_token:
    secure: WHW27Nvc8zNhfyhxIYdl/NwbrkFzvSX0vE4/CS8iByPXM6rcztWhUrDXJ7eejLBY
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only